# Generated by Django 5.1.5 on 2025-02-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_lesson_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
    ]
