# Generated by Django 5.1.5 on 2025-02-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_watchprogress_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'featured_order', '-updated']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Order in featured section'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this lesson in featured section'),
        ),
    ]
