# Generated by Django 5.1.5 on 2025-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_options_lesson_featured_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='If True, only paid subscribers can access this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview_time',
            field=models.PositiveIntegerField(default=0, help_text='Preview time in seconds for premium videos (0 for no preview)'),
        ),
    ]
