# Generated by Django 5.1.9 on 2025-05-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_credit_refill',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_depleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
