# Generated by Django 5.1.9 on 2025-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_builder_data_alter_message_input_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='dominant_emotion',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='emotion_metrics',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='personality_metrics',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='communication',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='confidence',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='emotions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='overallPattern',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='patterns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='prediction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='riskLevel',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='risks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='builder_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='isEmotionAnalysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('ai', 'AI'), ('architect', 'Architect'), ('loading', 'Loading')], max_length=20, null=True),
        ),
    ]
