# Generated by Django 5.1.9 on 2025-05-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_conversation_message_messageanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='openai_response',
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.TextField()),
                ('suggestions', models.JSONField()),
                ('personality_metrics', models.JSONField()),
                ('emotion_metrics', models.JSONField()),
                ('dominant_emotion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.conversation')),
            ],
        ),
    ]
