# Generated by Django 5.1.9 on 2025-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_conversationanalysis_dominant_emotion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='builder_message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isEmotionAnalysis',
        ),
        migrations.AddField(
            model_name='message',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('builder', 'Builder'), ('analysis', 'Analysis'), ('system', 'System'), ('loading', 'Loading')], default='user', max_length=20),
            preserve_default=False,
        ),
    ]
