# Generated by Django 5.1.9 on 2025-05-23 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_message_openai_response_conversationanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_credit_refill',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
