# Generated by Django 5.1.9 on 2025-06-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageanalysis',
            name='message',
        ),
        migrations.DeleteModel(
            name='ConversationAnalysis',
        ),
        migrations.DeleteModel(
            name='MessageAnalysis',
        ),
    ]
