# Generated by Django 5.1.9 on 2025-05-23 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_credits_customuser_last_credit_refill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_credit_refill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
