# Generated by Django 5.1.9 on 2025-06-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_messageanalysis_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('builder', 'Builder'), ('analysis', 'Analysis'), ('system', 'System'), ('loading', 'Loading')], max_length=20),
        ),
    ]
