# Generated by Django 5.1.9 on 2025-06-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_creditproduct_creditpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='creditpurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditProduct',
        ),
        migrations.DeleteModel(
            name='CreditPurchase',
        ),
    ]
