# Generated by Django 5.1.9 on 2025-07-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_provider_vault_embedding_providerreview_providertag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
