# Generated by Django 5.1.9 on 2025-07-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_provider_approved_provider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('qualifications', models.JSONField(blank=True, default=dict)),
                ('social_profiles', models.JSONField(blank=True, default=list)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('travel_option', models.CharField(blank=True, max_length=50, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=255, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.provider')),
            ],
        ),
    ]
