# Generated by Django 5.1.9 on 2025-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_serviceoffering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffering',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='serviceoffering',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='serviceoffering',
            name='social_profiles',
        ),
        migrations.AddField(
            model_name='provider',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='qualifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='provider',
            name='social_profiles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
