# Generated by Django 5.1.9 on 2025-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_serviceoffering_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='tone',
        ),
    ]
