# Generated by Django 5.1.9 on 2025-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_provider_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='offerings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
