# Generated by Django 5.1.9 on 2025-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_serviceoffering_offerings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffering',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
