# Generated by Django 5.1.9 on 2025-07-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_serviceoffering_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='icon',
        ),
    ]
