# Generated by Django 5.1.9 on 2025-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_vault_active_remove_vault_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffering',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='serviceoffering',
            name='service_type',
        ),
        migrations.AddField(
            model_name='provider',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
