# Generated by Django 5.1.9 on 2025-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_serviceoffering_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
