# Generated by Django 5.1.9 on 2025-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_provider_icon_serviceoffering_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='serviceoffering',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='provider',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
