# Generated by Django 5.1.9 on 2025-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_provider_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
