# Generated by Django 5.1.9 on 2025-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_provider_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='completion_count',
            field=models.IntegerField(default=0),
        ),
    ]
