# Generated by Django 5.1.9 on 2025-07-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_provider_completion_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('initial_chat', 'Initial Chat'), ('chat', 'Chat'), ('booking', 'Booking'), ('afterpayment', 'Afterpayment'), ('system', 'System'), ('loading', 'Loading'), ('companion_cards', 'Companion Cards'), ('companion_cards_select', 'Companion Cards Select'), ('loading_companion_cards', 'Loading Companion Cards')], max_length=25),
        ),
    ]
