# Generated by Django 5.1.9 on 2025-07-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='analysis_data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='builder_data',
        ),
    ]
