# Generated by Django 5.1.9 on 2025-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_message_search_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('image_upload', 'Image Upload'), ('social_link_upload', 'Social Link Upload'), ('json', 'JSON')], max_length=20),
        ),
    ]
