# Generated by Django 5.1.9 on 2025-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='language_support',
            new_name='languages',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='timezone',
        ),
        migrations.AddField(
            model_name='provider',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
