# Generated by Django 5.1.9 on 2025-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_message_currency_message_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='companion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
