# Generated by Django 5.1.9 on 2025-07-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_message_companion_id_message_date_message_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time',
            new_name='booking_time',
        ),
    ]
