apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/goldmage/django-k8s:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: django-k8s-prod-env
        env:
          - name: PORT
            value: "8002"
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: goldmage


---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-name: "52-do"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Optional, improves traffic handling and client IP retention
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8002
  selector:
    app: django-k8s-web-deployment