apiVersion: apps/v1
kind: Deployment
metadata:
  name: popup-store-1-deployment
  labels:
    app: popup-store-1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: popup-store-1-deployment
  template:
    metadata:
      labels:
        app: popup-store-1-deployment
    spec:
      containers:
      - name: popup-store-1
        image: registry.digitalocean.com/goldmage/popup-store-1:latest  # You'll change this to your new site's image
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: popup-store-1-env  # You'll create this secret for the new site's environment variables
        env:
          - name: PORT
            value: "8002"
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: goldmage  # Reusing the same registry secret since it's the same registry

---
apiVersion: v1
kind: Service
metadata:
  name: popup-store-1-deployment
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-name: "soleso"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8002
  selector:
    app: popup-store-1-deployment 