# Generated by Django 5.1.5 on 2025-02-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('emails', '0003_emailverificationevent_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='email',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='email_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='email',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='email',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='email_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
