# Generated by Django 5.1.5 on 2025-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_rename_active_email_is_active_email_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
