# Generated by Django 5.1.5 on 2025-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_email_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', help_text='Type of account subscription', max_length=10),
        ),
    ]
