# Generated by Django 5.1.5 on 2025-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_email_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=100, null=True),
        ),
    ]
