# Generated by Django 5.1.5 on 2025-02-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='country',
        ),
    ]
