name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  django_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
      CLOUDINARY_SECRET_API_KEY: test-key-not-good-maybe-make-one-better
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test